### ISSUE TITLE
Host on CallbackHandler should be optional

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse-python#27]
```
from langfuse.callback import CallbackHandler
handler = CallbackHandler(PUBLIC_KEY, SECRET_KEY)
```
Currently need to manually set `host=None` as positional argument is required

**Comment by Dev-Khant** [comment]
I'll pick it up @marcklingen

**Comment by Dev-Khant** [comment]
If we set `host=None` then won't it cause issue or should we set by default to `https://cloud.langfuse.com/` @marcklingen @maxdeichmann

**Comment by Dev-Khant** [comment]
@marcklingen I just saw you made the changes for it.
