### ISSUE TITLE
Add end() method to spans and generations

### ISSUE THREAD

**Issue by maxdeichmann** [langfuse/langfuse-python#30]
Users want to be able to  quickly `end` spans and generations. 

```
generation = langfuse.generation(...)
generation.end()

```
- [ ] For `StatefulGenerationClient` and `StatefulSpanClient`, add `end()` methods, send `endTime` to the Langfuse server. Under the hood, they can use the existing `update` functions.
- [ ] Create test coverage for both of the functions

**Comment by marcklingen** [comment]
Should this method still accept the update body excluding the endTime (optionally)?

**Comment by maxdeichmann** [comment]
> Should this method still accept the update body excluding the endTime (optionally)?

You mean it should take an object that takes everything except the endTime? Sure, we can do this.

**Comment by Dev-Khant** [comment]
@marcklingen @maxdeichmann This function is added!

**Comment by Dev-Khant** [comment]
It can be closed now @maxdeichmann
